//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.04 at 01:23:11 AM EEST 
//


package com.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Jewel }
     * 
     */
    public Jewel createJewel() {
        return new Jewel();
    }

    /**
     * Create an instance of {@link Jewel.Gem }
     * 
     */
    public Jewel.Gem createJewelGem() {
        return new Jewel.Gem();
    }

    /**
     * Create an instance of {@link Jewel.Gem.VisualParameters }
     * 
     */
    public Jewel.Gem.VisualParameters createJewelGemVisualParameters() {
        return new Jewel.Gem.VisualParameters();
    }

}
